name: 'DrupalX Standard'
description: 'Drupal configuration for standard Twig-based sites.'
type: 'Site'

install:
  - components
  - drupalx_ai
  - drupalx_theme
  - twig_field_value
  - twig_tweak

config:
  actions:
    system.site:
      simple_config_update:
        page.front: /node/16
    node.settings:
      simple_config_update:
        use_admin_theme: true
    system.theme:
      simple_config_update:
        admin: 'gin'
        default: 'drupalx_theme'
